log created at 2014-03-09 22:47:00 +0400[Sun Mar 09 23:32:17 2014] [error] [client 78.109.39.227] mod_wsgi (pid=22490): Exception occurred processing WSGI script '/home/hosting_mmailm/projects/irgid/django.wsgi'.
[Sun Mar 09 23:32:17 2014] [error] [client 78.109.39.227] Traceback (most recent call last):
[Sun Mar 09 23:32:17 2014] [error] [client 78.109.39.227]   File "/var/www/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 236, in __call__
[Sun Mar 09 23:32:17 2014] [error] [client 78.109.39.227]     self.load_middleware()
[Sun Mar 09 23:32:17 2014] [error] [client 78.109.39.227]   File "/var/www/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 45, in load_middleware
[Sun Mar 09 23:32:17 2014] [error] [client 78.109.39.227]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Sun Mar 09 23:32:17 2014] [error] [client 78.109.39.227]   File "/var/www/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
[Sun Mar 09 23:32:17 2014] [error] [client 78.109.39.227]     self._setup(name)
[Sun Mar 09 23:32:17 2014] [error] [client 78.109.39.227]   File "/var/www/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in _setup
[Sun Mar 09 23:32:17 2014] [error] [client 78.109.39.227]     self._wrapped = Settings(settings_module)
[Sun Mar 09 23:32:17 2014] [error] [client 78.109.39.227]   File "/var/www/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 132, in __init__
[Sun Mar 09 23:32:17 2014] [error] [client 78.109.39.227]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sun Mar 09 23:32:17 2014] [error] [client 78.109.39.227]   File "/var/www/home/hosting_mmailm/env/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
[Sun Mar 09 23:32:17 2014] [error] [client 78.109.39.227]     __import__(name)
[Sun Mar 09 23:32:17 2014] [error] [client 78.109.39.227]   File "/var/www/home/hosting_mmailm/projects/irgid/app/settings.py", line 17, in <module>
[Sun Mar 09 23:32:17 2014] [error] [client 78.109.39.227]     from settings_db import *
[Sun Mar 09 23:32:17 2014] [error] [client 78.109.39.227]   File "/var/www/home/hosting_mmailm/projects/irgid/app/settings_db.py", line 7
[Sun Mar 09 23:32:17 2014] [error] [client 78.109.39.227]     'USER': 'mmailm_irgid1',
[Sun Mar 09 23:32:17 2014] [error] [client 78.109.39.227]           ^
[Sun Mar 09 23:32:17 2014] [error] [client 78.109.39.227] SyntaxError: invalid syntax
[Sun Mar 09 23:33:42 2014] [error] [client 78.109.39.227] mod_wsgi (pid=26687): Exception occurred processing WSGI script '/home/hosting_mmailm/projects/irgid/django.wsgi'.
[Sun Mar 09 23:33:42 2014] [error] [client 78.109.39.227] Traceback (most recent call last):
[Sun Mar 09 23:33:42 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 236, in __call__
[Sun Mar 09 23:33:42 2014] [error] [client 78.109.39.227]     self.load_middleware()
[Sun Mar 09 23:33:42 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 45, in load_middleware
[Sun Mar 09 23:33:42 2014] [error] [client 78.109.39.227]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Sun Mar 09 23:33:42 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
[Sun Mar 09 23:33:42 2014] [error] [client 78.109.39.227]     self._setup(name)
[Sun Mar 09 23:33:42 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in _setup
[Sun Mar 09 23:33:42 2014] [error] [client 78.109.39.227]     self._wrapped = Settings(settings_module)
[Sun Mar 09 23:33:42 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 132, in __init__
[Sun Mar 09 23:33:42 2014] [error] [client 78.109.39.227]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sun Mar 09 23:33:42 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
[Sun Mar 09 23:33:42 2014] [error] [client 78.109.39.227]     __import__(name)
[Sun Mar 09 23:33:42 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/projects/irgid/app/settings.py", line 17, in <module>
[Sun Mar 09 23:33:42 2014] [error] [client 78.109.39.227]     from settings_db import *
[Sun Mar 09 23:33:42 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/projects/irgid/app/settings_db.py", line 7
[Sun Mar 09 23:33:42 2014] [error] [client 78.109.39.227]     'USER': 'mmailm_irgid1',
[Sun Mar 09 23:33:42 2014] [error] [client 78.109.39.227]           ^
[Sun Mar 09 23:33:42 2014] [error] [client 78.109.39.227] SyntaxError: invalid syntax
[Sun Mar 09 23:33:43 2014] [error] [client 78.109.39.227] mod_wsgi (pid=26687): Exception occurred processing WSGI script '/home/hosting_mmailm/projects/irgid/django.wsgi'.
[Sun Mar 09 23:33:43 2014] [error] [client 78.109.39.227] Traceback (most recent call last):
[Sun Mar 09 23:33:43 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 236, in __call__
[Sun Mar 09 23:33:43 2014] [error] [client 78.109.39.227]     self.load_middleware()
[Sun Mar 09 23:33:43 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 45, in load_middleware
[Sun Mar 09 23:33:43 2014] [error] [client 78.109.39.227]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Sun Mar 09 23:33:43 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
[Sun Mar 09 23:33:43 2014] [error] [client 78.109.39.227]     self._setup(name)
[Sun Mar 09 23:33:43 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in _setup
[Sun Mar 09 23:33:43 2014] [error] [client 78.109.39.227]     self._wrapped = Settings(settings_module)
[Sun Mar 09 23:33:43 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 132, in __init__
[Sun Mar 09 23:33:43 2014] [error] [client 78.109.39.227]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sun Mar 09 23:33:43 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
[Sun Mar 09 23:33:43 2014] [error] [client 78.109.39.227]     __import__(name)
[Sun Mar 09 23:33:43 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/projects/irgid/app/settings.py", line 17, in <module>
[Sun Mar 09 23:33:43 2014] [error] [client 78.109.39.227]     from settings_db import *
[Sun Mar 09 23:33:43 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/projects/irgid/app/settings_db.py", line 7
[Sun Mar 09 23:33:43 2014] [error] [client 78.109.39.227]     'USER': 'mmailm_irgid1',
[Sun Mar 09 23:33:43 2014] [error] [client 78.109.39.227]           ^
[Sun Mar 09 23:33:43 2014] [error] [client 78.109.39.227] SyntaxError: invalid syntax
[Sun Mar 09 23:33:45 2014] [error] [client 78.109.39.227] mod_wsgi (pid=26687): Exception occurred processing WSGI script '/home/hosting_mmailm/projects/irgid/django.wsgi'.
[Sun Mar 09 23:33:45 2014] [error] [client 78.109.39.227] Traceback (most recent call last):
[Sun Mar 09 23:33:45 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 236, in __call__
[Sun Mar 09 23:33:45 2014] [error] [client 78.109.39.227]     self.load_middleware()
[Sun Mar 09 23:33:45 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 45, in load_middleware
[Sun Mar 09 23:33:45 2014] [error] [client 78.109.39.227]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Sun Mar 09 23:33:45 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
[Sun Mar 09 23:33:45 2014] [error] [client 78.109.39.227]     self._setup(name)
[Sun Mar 09 23:33:45 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in _setup
[Sun Mar 09 23:33:45 2014] [error] [client 78.109.39.227]     self._wrapped = Settings(settings_module)
[Sun Mar 09 23:33:45 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 132, in __init__
[Sun Mar 09 23:33:45 2014] [error] [client 78.109.39.227]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sun Mar 09 23:33:45 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
[Sun Mar 09 23:33:45 2014] [error] [client 78.109.39.227]     __import__(name)
[Sun Mar 09 23:33:45 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/projects/irgid/app/settings.py", line 17, in <module>
[Sun Mar 09 23:33:45 2014] [error] [client 78.109.39.227]     from settings_db import *
[Sun Mar 09 23:33:45 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/projects/irgid/app/settings_db.py", line 7
[Sun Mar 09 23:33:45 2014] [error] [client 78.109.39.227]     'USER': 'mmailm_irgid1',
[Sun Mar 09 23:33:45 2014] [error] [client 78.109.39.227]           ^
[Sun Mar 09 23:33:45 2014] [error] [client 78.109.39.227] SyntaxError: invalid syntax
[Sun Mar 09 23:34:16 2014] [error] [client 78.109.39.227] mod_wsgi (pid=26687): Exception occurred processing WSGI script '/home/hosting_mmailm/projects/irgid/django.wsgi'.
[Sun Mar 09 23:34:16 2014] [error] [client 78.109.39.227] Traceback (most recent call last):
[Sun Mar 09 23:34:16 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 236, in __call__
[Sun Mar 09 23:34:16 2014] [error] [client 78.109.39.227]     self.load_middleware()
[Sun Mar 09 23:34:16 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 45, in load_middleware
[Sun Mar 09 23:34:16 2014] [error] [client 78.109.39.227]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Sun Mar 09 23:34:16 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
[Sun Mar 09 23:34:16 2014] [error] [client 78.109.39.227]     self._setup(name)
[Sun Mar 09 23:34:16 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in _setup
[Sun Mar 09 23:34:16 2014] [error] [client 78.109.39.227]     self._wrapped = Settings(settings_module)
[Sun Mar 09 23:34:16 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 132, in __init__
[Sun Mar 09 23:34:16 2014] [error] [client 78.109.39.227]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sun Mar 09 23:34:16 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
[Sun Mar 09 23:34:16 2014] [error] [client 78.109.39.227]     __import__(name)
[Sun Mar 09 23:34:16 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/projects/irgid/app/settings.py", line 17, in <module>
[Sun Mar 09 23:34:16 2014] [error] [client 78.109.39.227]     from settings_db import *
[Sun Mar 09 23:34:16 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/projects/irgid/app/settings_db.py", line 7
[Sun Mar 09 23:34:16 2014] [error] [client 78.109.39.227]     'USER': 'mmailm_irgid1',
[Sun Mar 09 23:34:16 2014] [error] [client 78.109.39.227]           ^
[Sun Mar 09 23:34:16 2014] [error] [client 78.109.39.227] SyntaxError: invalid syntax
[Sun Mar 09 23:34:27 2014] [error] [client 78.109.39.227] mod_wsgi (pid=26687): Exception occurred processing WSGI script '/home/hosting_mmailm/projects/irgid/django.wsgi'.
[Sun Mar 09 23:34:27 2014] [error] [client 78.109.39.227] Traceback (most recent call last):
[Sun Mar 09 23:34:27 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 236, in __call__
[Sun Mar 09 23:34:27 2014] [error] [client 78.109.39.227]     self.load_middleware()
[Sun Mar 09 23:34:27 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 45, in load_middleware
[Sun Mar 09 23:34:27 2014] [error] [client 78.109.39.227]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Sun Mar 09 23:34:27 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
[Sun Mar 09 23:34:27 2014] [error] [client 78.109.39.227]     self._setup(name)
[Sun Mar 09 23:34:27 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in _setup
[Sun Mar 09 23:34:27 2014] [error] [client 78.109.39.227]     self._wrapped = Settings(settings_module)
[Sun Mar 09 23:34:27 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 132, in __init__
[Sun Mar 09 23:34:27 2014] [error] [client 78.109.39.227]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sun Mar 09 23:34:27 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
[Sun Mar 09 23:34:27 2014] [error] [client 78.109.39.227]     __import__(name)
[Sun Mar 09 23:34:27 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/projects/irgid/app/settings.py", line 17, in <module>
[Sun Mar 09 23:34:27 2014] [error] [client 78.109.39.227]     from settings_db import *
[Sun Mar 09 23:34:27 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/projects/irgid/app/settings_db.py", line 7
[Sun Mar 09 23:34:27 2014] [error] [client 78.109.39.227]     'USER': 'mmailm_irgid1',
[Sun Mar 09 23:34:27 2014] [error] [client 78.109.39.227]           ^
[Sun Mar 09 23:34:27 2014] [error] [client 78.109.39.227] SyntaxError: invalid syntax
[Sun Mar 09 23:35:56 2014] [error] [client 78.109.39.227] mod_wsgi (pid=26687): Exception occurred processing WSGI script '/home/hosting_mmailm/projects/irgid/django.wsgi'.
[Sun Mar 09 23:35:56 2014] [error] [client 78.109.39.227] Traceback (most recent call last):
[Sun Mar 09 23:35:56 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 236, in __call__
[Sun Mar 09 23:35:56 2014] [error] [client 78.109.39.227]     self.load_middleware()
[Sun Mar 09 23:35:56 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 45, in load_middleware
[Sun Mar 09 23:35:56 2014] [error] [client 78.109.39.227]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Sun Mar 09 23:35:56 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
[Sun Mar 09 23:35:56 2014] [error] [client 78.109.39.227]     self._setup(name)
[Sun Mar 09 23:35:56 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in _setup
[Sun Mar 09 23:35:56 2014] [error] [client 78.109.39.227]     self._wrapped = Settings(settings_module)
[Sun Mar 09 23:35:56 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 132, in __init__
[Sun Mar 09 23:35:56 2014] [error] [client 78.109.39.227]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sun Mar 09 23:35:56 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
[Sun Mar 09 23:35:56 2014] [error] [client 78.109.39.227]     __import__(name)
[Sun Mar 09 23:35:56 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/projects/irgid/app/settings.py", line 17, in <module>
[Sun Mar 09 23:35:56 2014] [error] [client 78.109.39.227]     from settings_db import *
[Sun Mar 09 23:35:56 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/projects/irgid/app/settings_db.py", line 7
[Sun Mar 09 23:35:56 2014] [error] [client 78.109.39.227]     'USER': 'mmailm_irgid1',
[Sun Mar 09 23:35:56 2014] [error] [client 78.109.39.227]           ^
[Sun Mar 09 23:35:56 2014] [error] [client 78.109.39.227] SyntaxError: invalid syntax
[Sun Mar 09 23:37:13 2014] [error] [client 78.109.39.227] mod_wsgi (pid=26687): Exception occurred processing WSGI script '/home/hosting_mmailm/projects/irgid/django.wsgi'.
[Sun Mar 09 23:37:13 2014] [error] [client 78.109.39.227] Traceback (most recent call last):
[Sun Mar 09 23:37:13 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 236, in __call__
[Sun Mar 09 23:37:13 2014] [error] [client 78.109.39.227]     self.load_middleware()
[Sun Mar 09 23:37:13 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 45, in load_middleware
[Sun Mar 09 23:37:13 2014] [error] [client 78.109.39.227]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Sun Mar 09 23:37:13 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
[Sun Mar 09 23:37:13 2014] [error] [client 78.109.39.227]     self._setup(name)
[Sun Mar 09 23:37:13 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in _setup
[Sun Mar 09 23:37:13 2014] [error] [client 78.109.39.227]     self._wrapped = Settings(settings_module)
[Sun Mar 09 23:37:13 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 132, in __init__
[Sun Mar 09 23:37:13 2014] [error] [client 78.109.39.227]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sun Mar 09 23:37:13 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
[Sun Mar 09 23:37:13 2014] [error] [client 78.109.39.227]     __import__(name)
[Sun Mar 09 23:37:13 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/projects/irgid/app/settings.py", line 17, in <module>
[Sun Mar 09 23:37:13 2014] [error] [client 78.109.39.227]     from settings_db import *
[Sun Mar 09 23:37:13 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/projects/irgid/app/settings_db.py", line 7
[Sun Mar 09 23:37:13 2014] [error] [client 78.109.39.227]     'USER': 'mmailm_irgid1',
[Sun Mar 09 23:37:13 2014] [error] [client 78.109.39.227]           ^
[Sun Mar 09 23:37:13 2014] [error] [client 78.109.39.227] SyntaxError: invalid syntax
[Sun Mar 09 23:37:42 2014] [error] [client 78.109.39.227] mod_wsgi (pid=26687): Exception occurred processing WSGI script '/home/hosting_mmailm/projects/irgid/django.wsgi'.
[Sun Mar 09 23:37:42 2014] [error] [client 78.109.39.227] Traceback (most recent call last):
[Sun Mar 09 23:37:42 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 236, in __call__
[Sun Mar 09 23:37:42 2014] [error] [client 78.109.39.227]     self.load_middleware()
[Sun Mar 09 23:37:42 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 45, in load_middleware
[Sun Mar 09 23:37:42 2014] [error] [client 78.109.39.227]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Sun Mar 09 23:37:42 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
[Sun Mar 09 23:37:42 2014] [error] [client 78.109.39.227]     self._setup(name)
[Sun Mar 09 23:37:42 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in _setup
[Sun Mar 09 23:37:42 2014] [error] [client 78.109.39.227]     self._wrapped = Settings(settings_module)
[Sun Mar 09 23:37:42 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/__init__.py", line 132, in __init__
[Sun Mar 09 23:37:42 2014] [error] [client 78.109.39.227]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sun Mar 09 23:37:42 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
[Sun Mar 09 23:37:42 2014] [error] [client 78.109.39.227]     __import__(name)
[Sun Mar 09 23:37:42 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/projects/irgid/app/settings.py", line 17, in <module>
[Sun Mar 09 23:37:42 2014] [error] [client 78.109.39.227]     from settings_db import *
[Sun Mar 09 23:37:42 2014] [error] [client 78.109.39.227]   File "/home/hosting_mmailm/projects/irgid/app/settings_db.py", line 7
[Sun Mar 09 23:37:42 2014] [error] [client 78.109.39.227]     'USER': 'mmailm_irgid1',
[Sun Mar 09 23:37:42 2014] [error] [client 78.109.39.227]           ^
[Sun Mar 09 23:37:42 2014] [error] [client 78.109.39.227] SyntaxError: invalid syntax
[Sun Mar 09 14:44:31 2014] [error] Internal Server Error: /
[Sun Mar 09 14:44:31 2014] [error] Traceback (most recent call last):
[Sun Mar 09 14:44:31 2014] [error]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 103, in get_response
[Sun Mar 09 14:44:31 2014] [error]     resolver_match = resolver.resolve(request.path_info)
[Sun Mar 09 14:44:31 2014] [error]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 319, in resolve
[Sun Mar 09 14:44:31 2014] [error]     for pattern in self.url_patterns:
[Sun Mar 09 14:44:31 2014] [error]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 347, in url_patterns
[Sun Mar 09 14:44:31 2014] [error]     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
[Sun Mar 09 14:44:31 2014] [error]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 342, in urlconf_module
[Sun Mar 09 14:44:31 2014] [error]     self._urlconf_module = import_module(self.urlconf_name)
[Sun Mar 09 14:44:31 2014] [error]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
[Sun Mar 09 14:44:31 2014] [error]     __import__(name)
[Sun Mar 09 14:44:31 2014] [error] ImportError: No module named prj.urls
[Sun Mar 09 14:44:54 2014] [error] Internal Server Error: /
[Sun Mar 09 14:44:54 2014] [error] Traceback (most recent call last):
[Sun Mar 09 14:44:54 2014] [error]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 103, in get_response
[Sun Mar 09 14:44:54 2014] [error]     resolver_match = resolver.resolve(request.path_info)
[Sun Mar 09 14:44:54 2014] [error]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 319, in resolve
[Sun Mar 09 14:44:54 2014] [error]     for pattern in self.url_patterns:
[Sun Mar 09 14:44:54 2014] [error]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 347, in url_patterns
[Sun Mar 09 14:44:54 2014] [error]     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
[Sun Mar 09 14:44:54 2014] [error]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 342, in urlconf_module
[Sun Mar 09 14:44:54 2014] [error]     self._urlconf_module = import_module(self.urlconf_name)
[Sun Mar 09 14:44:54 2014] [error]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
[Sun Mar 09 14:44:54 2014] [error]     __import__(name)
[Sun Mar 09 14:44:54 2014] [error] ImportError: No module named prj.urls
[Mon Mar 10 04:50:56 2014] [error] /home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/urls/defaults.py:3: DeprecationWarning: django.conf.urls.defaults is deprecated; use django.conf.urls instead
[Mon Mar 10 04:50:56 2014] [error]   DeprecationWarning)
[Mon Mar 10 04:50:56 2014] [error] 
[Mon Mar 10 04:50:56 2014] [error] /home/hosting_mmailm/env/lib/python2.7/site-packages/mptt/models.py:305: DeprecationWarning: Implicit manager CMSPlugin.tree will be removed in django-mptt 0.6.  Explicitly define a TreeManager() on your model to remove this warning.
[Mon Mar 10 04:50:56 2014] [error]   DeprecationWarning
[Mon Mar 10 04:50:56 2014] [error] 
[Mon Mar 10 04:50:56 2014] [error] Internal Server Error: /
[Mon Mar 10 04:50:56 2014] [error] Traceback (most recent call last):
[Mon Mar 10 04:50:56 2014] [error]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 103, in get_response
[Mon Mar 10 04:50:56 2014] [error]     resolver_match = resolver.resolve(request.path_info)
[Mon Mar 10 04:50:56 2014] [error]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 319, in resolve
[Mon Mar 10 04:50:56 2014] [error]     for pattern in self.url_patterns:
[Mon Mar 10 04:50:56 2014] [error]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 347, in url_patterns
[Mon Mar 10 04:50:56 2014] [error]     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
[Mon Mar 10 04:50:56 2014] [error]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 342, in urlconf_module
[Mon Mar 10 04:50:56 2014] [error]     self._urlconf_module = import_module(self.urlconf_name)
[Mon Mar 10 04:50:56 2014] [error]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
[Mon Mar 10 04:50:56 2014] [error]     __import__(name)
[Mon Mar 10 04:50:56 2014] [error]   File "/home/hosting_mmailm/projects/irgid/app/urls.py", line 8, in <module>
[Mon Mar 10 04:50:56 2014] [error]     admin.autodiscover()
[Mon Mar 10 04:50:56 2014] [error]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
[Mon Mar 10 04:50:56 2014] [error]     import_module('%s.admin' % app)
[Mon Mar 10 04:50:56 2014] [error]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
[Mon Mar 10 04:50:56 2014] [error]     __import__(name)
[Mon Mar 10 04:50:56 2014] [error]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/contrib/auth/admin.py", line 179, in <module>
[Mon Mar 10 04:50:56 2014] [error]     admin.site.register(Group, GroupAdmin)
[Mon Mar 10 04:50:56 2014] [error]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 98, in register
[Mon Mar 10 04:50:56 2014] [error]     validate(admin_class, model)
[Mon Mar 10 04:50:56 2014] [error]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/contrib/admin/validation.py", line 22, in validate
[Mon Mar 10 04:50:56 2014] [error]     models.get_apps()
[Mon Mar 10 04:50:56 2014] [error]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/db/models/loading.py", line 134, in get_apps
[Mon Mar 10 04:50:56 2014] [error]     self._populate()
[Mon Mar 10 04:50:56 2014] [error]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/db/models/loading.py", line 72, in _populate
[Mon Mar 10 04:50:56 2014] [error]     self.load_app(app_name, True)
[Mon Mar 10 04:50:56 2014] [error]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/db/models/loading.py", line 94, in load_app
[Mon Mar 10 04:50:56 2014] [error]     app_module = import_module(app_name)
[Mon Mar 10 04:50:56 2014] [error]   File "/home/hosting_mmailm/env/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
[Mon Mar 10 04:50:56 2014] [error]     __import__(name)
[Mon Mar 10 04:50:56 2014] [error] ImportError: No module named excursions
[Mon Mar 10 04:51:22 2014] [error] /home/hosting_mmailm/env/lib/python2.7/site-packages/django/contrib/markup/templatetags/markup.py:52: DeprecationWarning: The markdown filter has been deprecated
[Mon Mar 10 04:51:22 2014] [error]   category=DeprecationWarning)
[Mon Mar 10 04:51:22 2014] [error] 
[Mon Mar 10 04:57:59 2014] [error] /home/hosting_mmailm/env/lib/python2.7/site-packages/django/utils/text.py:214: DeprecationWarning: This function has been deprecated. Use the Truncator class in django.utils.text instead.
[Mon Mar 10 04:57:59 2014] [error]   'in django.utils.text instead.', category=DeprecationWarning)
[Mon Mar 10 04:57:59 2014] [error] 
[Mon Mar 10 13:40:32 2014] [error] /home/hosting_mmailm/env/lib/python2.7/site-packages/django/conf/urls/defaults.py:3: DeprecationWarning: django.conf.urls.defaults is deprecated; use django.conf.urls instead
[Mon Mar 10 13:40:32 2014] [error]   DeprecationWarning)
[Mon Mar 10 13:40:32 2014] [error] 
[Mon Mar 10 13:40:33 2014] [error] /home/hosting_mmailm/env/lib/python2.7/site-packages/mptt/models.py:305: DeprecationWarning: Implicit manager CMSPlugin.tree will be removed in django-mptt 0.6.  Explicitly define a TreeManager() on your model to remove this warning.
[Mon Mar 10 13:40:33 2014] [error]   DeprecationWarning
[Mon Mar 10 13:40:33 2014] [error] 
[Mon Mar 10 13:41:30 2014] [error] /home/hosting_mmailm/env/lib/python2.7/site-packages/django/contrib/markup/templatetags/markup.py:52: DeprecationWarning: The markdown filter has been deprecated
[Mon Mar 10 13:41:30 2014] [error]   category=DeprecationWarning)
[Mon Mar 10 13:41:30 2014] [error] 
